//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slot.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slot.Model.Resources.ErrorCode", typeof(ErrorCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified error..
        /// </summary>
        public static string _000 {
            get {
                return ResourceManager.GetString("_000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect lines number..
        /// </summary>
        public static string _001 {
            get {
                return ResourceManager.GetString("_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect bet..
        /// </summary>
        public static string _002 {
            get {
                return ResourceManager.GetString("_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect input..
        /// </summary>
        public static string _003 {
            get {
                return ResourceManager.GetString("_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonexistent bonus..
        /// </summary>
        public static string _004 {
            get {
                return ResourceManager.GetString("_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong parameters..
        /// </summary>
        public static string _005 {
            get {
                return ResourceManager.GetString("_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong bonus step..
        /// </summary>
        public static string _006 {
            get {
                return ResourceManager.GetString("_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user can&apos;t connect at the moment. Please try to relogin. If the problem persists, please contact our support..
        /// </summary>
        public static string _007 {
            get {
                return ResourceManager.GetString("_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing room for this user..
        /// </summary>
        public static string _008 {
            get {
                return ResourceManager.GetString("_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing group for this user..
        /// </summary>
        public static string _009 {
            get {
                return ResourceManager.GetString("_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient balance. Please place a lower bet or alternatively top up your account..
        /// </summary>
        public static string _010 {
            get {
                return ResourceManager.GetString("_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin error..
        /// </summary>
        public static string _011 {
            get {
                return ResourceManager.GetString("_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing game setting for this user..
        /// </summary>
        public static string _012 {
            get {
                return ResourceManager.GetString("_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonexistent hand..
        /// </summary>
        public static string _013 {
            get {
                return ResourceManager.GetString("_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong step..
        /// </summary>
        public static string _014 {
            get {
                return ResourceManager.GetString("_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect round..
        /// </summary>
        public static string _015 {
            get {
                return ResourceManager.GetString("_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect state..
        /// </summary>
        public static string _016 {
            get {
                return ResourceManager.GetString("_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error..
        /// </summary>
        public static string _017 {
            get {
                return ResourceManager.GetString("_017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login exist..
        /// </summary>
        public static string _018 {
            get {
                return ResourceManager.GetString("_018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonexistent user data..
        /// </summary>
        public static string _019 {
            get {
                return ResourceManager.GetString("_019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Maintenance..
        /// </summary>
        public static string _020 {
            get {
                return ResourceManager.GetString("_020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Maintenance..
        /// </summary>
        public static string _021 {
            get {
                return ResourceManager.GetString("_021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple logins on the same game detected. You will be logged-out from this game. Please proceed to other game. Thank you..
        /// </summary>
        public static string _024 {
            get {
                return ResourceManager.GetString("_024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Game.
        /// </summary>
        public static string _025 {
            get {
                return ResourceManager.GetString("_025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request is currently being processed..
        /// </summary>
        public static string _026 {
            get {
                return ResourceManager.GetString("_026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string _027 {
            get {
                return ResourceManager.GetString("_027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CheckSum.
        /// </summary>
        public static string _028 {
            get {
                return ResourceManager.GetString("_028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non existence free round bonus.
        /// </summary>
        public static string _029 {
            get {
                return ResourceManager.GetString("_029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non activation free round bous.
        /// </summary>
        public static string _030 {
            get {
                return ResourceManager.GetString("_030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Implemented.
        /// </summary>
        public static string _031 {
            get {
                return ResourceManager.GetString("_031", resourceCulture);
            }
        }
    }
}
