SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


/****** Object:  Index [IX_DateTimeUtc]    Script Date: 11/1/2018 3:18:47 PM ******/
CREATE NONCLUSTERED INDEX [IX_DateTimeUtc] ON [dbo].[GameHistory]
(
	[DateTimeUtc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)
GO

/****** Object:  Index [IX_GameId]    Script Date: 11/1/2018 3:18:54 PM ******/
CREATE NONCLUSTERED INDEX [IX_GameId] ON [dbo].[GameHistory]
(
	[GameId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)
GO

/****** Object:  Index [IX_GameTransactionId]    Script Date: 11/1/2018 3:19:01 PM ******/
CREATE NONCLUSTERED INDEX [IX_GameTransactionId] ON [dbo].[GameHistory]
(
	[GameTransactionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)
GO

/****** Object:  Index [IX_SpinTransactionId]    Script Date: 11/1/2018 3:19:11 PM ******/
CREATE NONCLUSTERED INDEX [IX_SpinTransactionId] ON [dbo].[GameHistory]
(
	[SpinTransactionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)
GO

/****** Object:  Index [IX_UserId]    Script Date: 11/1/2018 3:19:18 PM ******/
CREATE NONCLUSTERED INDEX [IX_UserId] ON [dbo].[GameHistory]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)
GO

/****** Object:  Index [IX_UserId_AND_GameId_AND_IsHistory]    Script Date: 11/1/2018 3:19:24 PM ******/
CREATE NONCLUSTERED INDEX [IX_UserId_AND_GameId_AND_IsHistory] ON [dbo].[GameHistory]
(
	[UserId] ASC,
	[GameId] ASC,
	[IsHistory] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)
GO
